name: citi_policemen
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  location: ^4.3.0
  permission_handler: ^8.1.4+2
  google_maps_flutter: 2.0.6
  pin_code_fields: ^7.3.0
  flutter_svg: ^0.22.0
  image_picker: ^0.8.3
  record_mp3: ^3.0.0
  audioplayers: ^0.20.1
  path_provider: ^2.0.0
  firebase_core: ^1.6.0
  fluttertoast: 8.0.7
  cloud_firestore: ^3.1.1
  firebase_auth: ^3.3.0
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.7
  http: ^0.13.3
  flutter_phone_direct_caller: ^2.1.0
  flutter_local_notifications: ^9.1.5
  firebase_messaging: ^11.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee.ttf
